image: node:14  # Imagem base para execução do pipeline (Node.js neste exemplo)

stages:
  - build
  - deploy

variables:
  PUBLIC_URL: "https://gitlab.com/ecohold/mex.git"  # Substitua <nome-do-repositório> pelo nome real do seu repositório

build:
  stage: build
  script:
    - echo "Construindo o projeto..."
    - npm install  # Instalar dependências, se necessário
    - npm run build  # Comando para construir o projeto (ex: compilar HTML, CSS, JavaScript)
  artifacts:
    paths:
      - public  # Pasta onde os arquivos construídos são colocados (geralmente "public" ou "build")
    expire_in: 1 week  # Configuração opcional para expiração dos artefatos

deploy:
  stage: deploy
  script:
    - echo "Implantando nas GitLab Pages..."
    - mkdir .public
    - cp -r public/* .public/
    - mv .public public
  artifacts:
    paths:
      - public  # Garante que a pasta "public" seja mantida como um artefato para a implantação
  environment:
    name: production  # Nome do ambiente (pode ser personalizado)
    url: https://ecohold.gitlab.io/mex/  # URL pública do seu site nas GitLab Pages
  only:
    - master  # Executa o pipeline apenas quando houver mudanças na branch "master"
