image: node:14

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - echo "Construindo o projeto..."
    - # Comandos para construir o seu projeto (ex: compilar HTML, CSS, JavaScript)
  artifacts:
    paths:
      - public/
    expire_in: 1 week
  only:
    - master

deploy:
  stage: deploy
  script:
    - echo "Implantando nas GitLab Pages..."
    - mkdir .public
    - cp -r * .public
    - mv .public public
  artifacts:
    paths:
      - public
  only:
    - master
