# Arquivo .gitlab-ci.yml

# Define a imagem base para as etapas do pipeline
image: node:14  # Exemplo com Node.js, ajuste conforme suas necessidades

# Define as etapas do pipeline
stages:
  - build
  - deploy

# Etapa de construção
build:
  stage: build
  script:
    - echo "Construindo o projeto..."
    - # Comandos para construir o seu projeto (ex: compilar HTML, CSS, JavaScript)
  artifacts:
    paths:
      - public/
    expire_in: 1 week  # Define quanto tempo os artefatos devem ser mantidos disponíveis
  only:
    - master  # Define que o pipeline será executado apenas quando houver push na branch master

# Etapa de implantação nas GitLab Pages
deploy:
  stage: deploy
  script:
    - echo "Implantando nas GitLab Pages..."
    - mkdir .public
    - cp -r * .public
    - mv .public public
  artifacts:
    paths:
      - public
  only:
    - master  # Define que a implantação será executada apenas quando houver push na branch master
